### ISSUE TITLE
SSL Verification -

### ISSUE THREAD

**Issue by cmurrayis** [madsbacha/routeros-vpn#3]
Script appears to not skip SSL verification:

No existing DNS entry exist for bahamas401
Creating static DNS entry for bahamas401
Added static dns entry bahamas401
DEBUG | Calling method $DoDelay
Delaying 1s seconds
DEBUG | seconds = 1s
failure: SSL: ssl: name verification failed for: "CN=bahamas.privacy.network" (6)

**Comment by madsbacha** [comment]
@cmurrayis should have been fixed now. If it still fails with the newest changes from the _main_ branch, we can reopen the issue.
