### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by xorinzor** [madsbacha/routeros-vpn#5]
I copied the script and edited the parameters, yet executing it results in this (I executed it 3 times sequentially to make sure there was no other log output from the script):

![image](https://github.com/user-attachments/assets/5558efa1-56ab-47ef-9428-a00c8a615dff)

Opening one of them doesn't show any additional information:
![image](https://github.com/user-attachments/assets/aff21a1d-7266-411a-b0ca-5ad3d25ea558)

Running this on my RB3011UiAS, do you have any idea what could be the issue?

**Comment by madsbacha** [comment]
Which RouterOS version are you running?

**Comment by xorinzor** [comment]
7.15.3

**Comment by madsbacha** [comment]
That's weird, it works without errors on my RB5009 running RouterOS 7.15.3. What happens when you run the script from the terminal?
Like `/system/script/run vpn-pia-berlin-1;` where `vpn-pia-berlin-1` is the name of the script.

**Comment by xorinzor** [comment]
Ah, cool. Now it does show me the exact position in the code where the error occurs, that's what I was searching for.

Appears to be the `pia-password` that's problematic, despite me escaping the `$` characters in my password.
I suppose there's some other problematic characters in it. Will try changing the password to something else.

**Comment by xorinzor** [comment]
Works now, thanks!
